import type { Project } from './types';
import generated from './projects.generated.json';

/**
 * Real PROJECTS dataset, derived from the author's GitHub repositories.
 *
 * Generated by scripts/build-projects.mjs from src/data/github/repos.snapshot.json
 * (a captured GitHub API response). This replaced the hand-authored mock
 * projects with real repo-derived data WITHOUT changing any visualization code —
 * the seam consumes the Project contract unchanged. Ids referenced by signals
 * (snto, fieldos, hati-madrid, radar) are preserved so relationships resolve.
 *
 * To refresh: update the snapshot, then `node scripts/build-projects.mjs`.
 */
export const projects: Project[] = generated as Project[];
