import type { Observation } from './types';
import generated from './snto.generated.json';

/**
 * Authentic SNTO NDVI observation slice (Phase 4C2A).
 *
 * Generated by scripts/build-snto-observations.mjs from the pinned, verbatim
 * snapshots under src/data/snto/ (see src/data/snto/SNAPSHOT.md). The three
 * records are the PNSG assets whose upstream geometry is genuinely `Point`, for
 * the 2026-06 monthly composite. Each value is an upstream Sentinel-2 NDVI zonal
 * aggregate (50 m buffer around the anchor); FAB recomputes nothing.
 *
 * To refresh: re-copy the snapshots from the pinned commit, then
 * `npm run data:snto`. Never hand-edit snto.generated.json.
 */
export const sntoObservations: Observation[] = generated as Observation[];
